In [2]:
#Insights----Importing the necessary libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
#Insights----File Path of dataset
df = pd.read_csv("/content/student-mat (4).csv")

In [6]:
# Printing first 5 rows
df.head()

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [7]:
#Printing last 5 rows
df.tail()

    school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
390  MS;"M";20;"U";"LE3";"A";2;2;"services";"servic...
391  MS;"M";17;"U";"LE3";"T";3;1;"services";"servic...
392  MS;"M";21;"R";"GT3";"T";1;1;"other";"other";"c...
393  MS;"M";18;"R";"LE3";"T";3;2;"services";"other"...
394  MS;"M";19;"U";"LE3";"T";1;1;"other";"at_home";...

In [8]:
#Information of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                               --------------  -----
 0   school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3  395 non-null    object
dtypes: object(1)
memory usage: 3.2+ KB

In [9]:
#Describing the given dataset
df.describe()

       school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
count                                                 395
unique                                                395
top     MS;"M";19;"U";"LE3";"T";1;1;"other";"at_home";...
freq                                                    1

In [11]:
import pandas as pd
df = pd.read_csv("/content/student-mat (4).csv", sep=";")
#Shape of dataset
print(df.head())
print(df.shape)

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]
(395, 33)

In [12]:
#Implementing Label Encoder
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [13]:
X = df.drop("G3", axis=1)
y = df["G3"]

In [14]:
#Implementing standard scaler
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [15]:
#Training and Testing the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))

model.add(Dense(32, activation='relu'))

model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
#Compilation Step
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [18]:
#Getting history
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 118.0655 - mae: 9.9219 - val_loss: 101.9213 - val_mae: 9.4059
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.0107 - mae: 8.7307 - val_loss: 73.6382 - val_mae: 7.9547
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.5388 - mae: 7.2855 - val_loss: 45.5952 - val_mae: 6.1492
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.0370 - mae: 5.4504 - val_loss: 23.5446 - val_mae: 4.2500
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.3302 - mae: 3.7015 - val_loss: 13.1712 - val_mae: 2.9935
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.7835 - mae: 2.6115 - val_loss: 10.7405 - val_mae: 2.4960
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9931 - mae: 2.1760 - val_loss: 9.1357 - val_mae: 2.3426
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5775 - mae: 2.0450 - val_loss: 8.1147 - val_mae: 2.2609
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.3958 - mae: 1.8922 - val_loss: 7.7063 - val_mae: 2.2185
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.6986 - mae: 1.7711 - val_loss: 7.4111 - val_mae: 2.1667
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.2258 - mae: 1.7000 - val_loss: 7.1118 - val_mae: 2.1407
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.7842 - mae: 1.6310 - val_loss: 6.9414 - val_mae: 2.1145
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4458 - mae: 1.5744 - val_loss: 6.8382 - val_mae: 2.0867
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.1578 - mae: 1.5227 - val_loss: 6.6683 - val_mae: 2.0570
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.8829 - mae: 1.4827 - val_loss: 6.6177 - val_mae: 2.0493
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.6282 - mae: 1.4352 - val_loss: 6.5024 - val_mae: 2.0191
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.4044 - mae: 1.3911 - val_loss: 6.5724 - val_mae: 2.0166
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1984 - mae: 1.3441 - val_loss: 6.4370 - val_mae: 1.9966
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0261 - mae: 1.3150 - val_loss: 6.2525 - val_mae: 1.9788
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.7915 - mae: 1.2608 - val_loss: 6.2688 - val_mae: 1.9577
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6173 - mae: 1.2147 - val_loss: 6.1618 - val_mae: 1.9330
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4456 - mae: 1.1711 - val_loss: 6.1348 - val_mae: 1.9334
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.2936 - mae: 1.1302 - val_loss: 6.1406 - val_mae: 1.9116
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1547 - mae: 1.0925 - val_loss: 6.0416 - val_mae: 1.8979
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.0231 - mae: 1.0512 - val_loss: 6.0030 - val_mae: 1.8745
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8896 - mae: 1.0099 - val_loss: 5.9390 - val_mae: 1.8672
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7751 - mae: 0.9771 - val_loss: 5.9172 - val_mae: 1.8533
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6645 - mae: 0.9459 - val_loss: 5.8705 - val_mae: 1.8376
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5704 - mae: 0.9131 - val_loss: 5.8798 - val_mae: 1.8338
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4788 - mae: 0.8810 - val_loss: 5.8230 - val_mae: 1.8239
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3894 - mae: 0.8483 - val_loss: 5.7325 - val_mae: 1.7984
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3107 - mae: 0.8288 - val_loss: 5.7336 - val_mae: 1.8056
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2377 - mae: 0.8016 - val_loss: 5.6367 - val_mae: 1.7851
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1667 - mae: 0.7781 - val_loss: 5.7924 - val_mae: 1.7900
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0830 - mae: 0.7431 - val_loss: 5.5440 - val_mae: 1.7529
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0232 - mae: 0.7213 - val_loss: 5.5852 - val_mae: 1.7583
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9586 - mae: 0.7011 - val_loss: 5.5692 - val_mae: 1.7531
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9043 - mae: 0.6796 - val_loss: 5.5173 - val_mae: 1.7295
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8462 - mae: 0.6587 - val_loss: 5.4743 - val_mae: 1.7244
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8026 - mae: 0.6400 - val_loss: 5.4141 - val_mae: 1.7162
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7587 - mae: 0.6243 - val_loss: 5.4664 - val_mae: 1.7154
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7098 - mae: 0.5994 - val_loss: 5.4050 - val_mae: 1.7019
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6765 - mae: 0.5920 - val_loss: 5.3414 - val_mae: 1.6938
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6364 - mae: 0.5717 - val_loss: 5.3721 - val_mae: 1.6959
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6001 - mae: 0.5565 - val_loss: 5.2699 - val_mae: 1.6880
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5674 - mae: 0.5358 - val_loss: 5.2748 - val_mae: 1.6804
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5261 - mae: 0.5198 - val_loss: 5.2338 - val_mae: 1.6811
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4935 - mae: 0.5052 - val_loss: 5.2889 - val_mae: 1.6839
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4680 - mae: 0.4897 - val_loss: 5.1940 - val_mae: 1.6749
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4371 - mae: 0.4742 - val_loss: 5.2141 - val_mae: 1.6754

In [19]:
#Loss Function
loss, mae = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Mean Absolute Error:", mae)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 7.9545 - mae: 2.0680
Test Loss: 7.954521179199219
Mean Absolute Error: 2.0680010318756104

In [20]:
#Printing the final predictions
predictions = model.predict(X_test)

print("Actual Grade:", y_test.iloc[0])
print("Predicted Grade:", predictions[0][0])

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Actual Grade: 10
Predicted Grade: 8.096387